function VisualizeExample1(viz_data, Problem)
    % Create separate figures for decision and objective spaces
    if ishandle(1) && strcmp(get(1, 'Type'), 'figure')
        disp('Figure 1 exists.');
        dec_fig = figure(1);
    else
        disp('Figure 1 does not exist.');
        dec_fig = figure('Position', [100, 100, 1200, 900], ...
                     'Name', 'Example 1: Decision Space Visualization');
    end

    if ishandle(2) && strcmp(get(2, 'Type'), 'figure')
        disp('Figure 2 exists.');
        obj_fig = figure(2);
    else
        disp('Figure 2 does not exist.');
        obj_fig = figure('Position', [110, 90, 1200, 900], ...
                         'Name', 'Example 1: Objective Space Visualization');
    end

    % Get the final iteration data
    current_iter = length(viz_data.Populations);
    
    % Plot Decision Space
    figure(dec_fig);
    dec_ax = axes('Position', [0.1, 0.1, 0.85, 0.85]);
    PlotDecisionSpace(current_iter, dec_ax, viz_data, Problem);
    print('./Visualization/images/Example1DecisionSpaceFN.eps','-depsc')

    % Plot Objective Space  
    figure(obj_fig);
    obj_ax = axes('Position', [0.1, 0.1, 0.85, 0.85]);
    PlotObjectiveSpace(current_iter, obj_ax, viz_data, Problem);
    print('./Visualization/images/Example1ObjectiveSpaceFN.eps','-depsc')
end

function PlotDecisionSpace(current_iter, ax, viz_data, Problem)
    % Route based on decision space dimension
    if Problem.D == 2
        DecisionPlot2D(current_iter, ax, viz_data, Problem);
    elseif Problem.D == 3
        DecisionPlot3D(current_iter, ax, viz_data, Problem);
    else
        error('Decision space visualization only supports D=2 or D=3. Got D=%d', Problem.D);
    end
end

function PlotObjectiveSpace(current_iter, ax, viz_data, Problem)
    % Route based on objective space dimension
    if Problem.M == 2
        ObjectivePlot2D(current_iter, ax, viz_data, Problem);
    elseif Problem.M == 3
        ObjectivePlot3D(current_iter, ax, viz_data, Problem);
    else
        error('Objective space visualization only supports M=2 or M=3. Got M=%d', Problem.M);
    end
end


%% DECISION SPACE PLOTTING
function DecisionPlot2D(current_iter, ax, viz_data, Problem)
    cla(ax, 'reset');
    hold(ax, 'on');
    grid(ax, 'on');
    
    %% Labels
    xlabel(ax, '$x_1$', 'Interpreter', 'latex');
    ylabel(ax, '$x_2$', 'Interpreter', 'latex');

    %% Titles
    % title(ax, 'Decision Space', 'FontSize', 14, 'FontWeight', 'bold');
    
    %% Contents (uisetcolor)
    neighbor_color = [0.9294    0.6941    0.1255];
    feasible_color = [0.2, 0.4, 0.8];
    infeasible_color = [0.8, 0.2, 0.2];
    final_color = [0.2, 0.6, 0.2];
    traj_color = [0.9, 0.3, 0.3];
    
    X0 = viz_data.Populations{current_iter};
    Neighbors = viz_data.Neighbors{current_iter};
    trajectory = viz_data.Trajectories{current_iter};
    
    %% (Content) Pareto Set
    PS = Problem.GetPS(100);
    h_PS = plot(ax, PS(:,1), PS(:,2), 'Color', 'k', 'LineWidth', 3);

    %% (Content) Neighbor set
    all_neighbor_decs = [];
    for i = 1:length(Neighbors)
        all_neighbor_decs = [all_neighbor_decs; Neighbors{i}.decs];
    end
    all_neighbor_decs = setdiff(all_neighbor_decs, X0.decs, 'rows');
    h_n = scatter(ax, ...
    all_neighbor_decs(:,1), all_neighbor_decs(:,2), ...
        'SizeData', 60, ...
        'CData', neighbor_color, ...
        'Marker', 'diamond', ...        % optional: defaults to 'o'
        'MarkerFaceColor', 'flat', ... % required to apply CData as face color
        'MarkerEdgeColor', neighbor_color, ...
        'MarkerFaceAlpha', 1);

    %% (Content) X0 set
    X0_feasible = all(X0.cons <= 0, 2)';X0_decs = X0.decs;
    h_fX0 = scatter(ax, ...
        X0_decs(X0_feasible,1), X0_decs(X0_feasible,2), ...
        'SizeData', 140, ...
        'CData', feasible_color, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'flat', ...
        'MarkerEdgeColor', 'none', ...
        'LineWidth', 1);
    h_ifX0 = scatter(ax, ...
        X0_decs(~X0_feasible,1), X0_decs(~X0_feasible,2), ...
        'SizeData', 140, ...
        'CData', feasible_color, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'none', ...
        'MarkerEdgeColor', feasible_color, ...
        'LineWidth', 3);
    
    %% (Content) GSA trajectories
    X1_feasible_plotted = false;X1_infeasible_plotted = false;
    pre = trajectory.pre;post = trajectory.post;
    h_dir = plot(ax, nan, nan, '-', ...
        'Color', traj_color, ...          % 1x3 RGB; lines don’t support RGBA
        'LineWidth', 3, ...
        'DisplayName', 'Normalized Direction');

    for j = 1:numel(pre)
        p0_decs = pre{j}.decs; num_tests = numel(post{j});
        for k = 1:num_tests
            p1_decs = post{j}(k).decs;
            % Calculate color based on step size
            t = (k-1)/(max(num_tests-1, 1));
            traj_color = [0.9 - 0.4*t, 0.3 - 0.2*t, 0.3 - 0.2*t];
            alpha = 1 - 0.5*t;
            
            %% (Content) GSA trajectory
            h_GSA = plot(ax, ...
                [p0_decs(1), p1_decs(1)], ...
                [p0_decs(2), p1_decs(2)], ...
                '-', 'Color', [traj_color, alpha], ...
                'LineWidth', 3);
            uistack(h_GSA, 'bottom');
        end
        p1_final = post{j}(end).decs;
        p1_feasible = all(post{j}(end).cons <= 0, 2);
        if p1_feasible
            %% (Content) Feasible solution
            h_fX1 = scatter(ax, ...
                p1_final(1), p1_final(2), ...
                'SizeData', 140, ...
                'CData', final_color, ...
                'Marker', '^', ...
                'MarkerFaceColor', 'flat', ...
                'MarkerEdgeColor', 'none', ...
                'LineWidth', 1);
        else
            %% (Content) Infeasible solution
            h_ifX1 = scatter(ax, ...
                p1_final(1), p1_final(2), ...
                'SizeData', 140, ...
                'CData', final_color, ...
                'Marker', '^', ...
                'MarkerFaceColor', 'none', ...
                'MarkerEdgeColor', final_color, ...
                'LineWidth', 3);
        end
    end
    uistack(h_PS, 'bottom');
    
    % Add legend
    legend([h_PS, h_n, h_fX0, h_ifX0, h_fX1, h_ifX1, h_GSA], ...
        {'True Pareto Set', ...
        'Neighbors', ...
        'Feasible Solutions ($X_0$)', ...
        'Infeasible Solutions ($X_0$)', ...
        'Feasible Solutions ($X_1$)', ...
        'Infeasible Solutions ($X_1$)', ...
        'GSA Trajectory'}, 'interpreter', 'latex');
    legend(ax, 'Location', 'best');

    set(gca, 'FontSize', 24, 'FontName', 'Times');
    
    % EnlargeFont();
end

%% OBJECTIVE SPACE PLOTTING
function ObjectivePlot2D(current_iter, ax, viz_data, Problem)
    cla(ax, 'reset');
    hold(ax, 'on');
    grid(ax, 'on');
    
    %% Labels
    xlabel(ax, '$f_1$', 'Interpreter', 'latex');
    ylabel(ax, '$f_2$', 'Interpreter', 'latex');

    %% Titles
    % title(ax, 'Objective Space', 'FontSize', 14, 'FontWeight', 'bold');
    
    %% Contents (uisetcolor)
    neighbor_color = [0.9294    0.6941    0.1255];
    feasible_color = [0.2, 0.4, 0.8];
    infeasible_color = [0.8, 0.2, 0.2];
    final_color = [0.2, 0.6, 0.2];
    traj_color = [0.9, 0.3, 0.3];
    ref_color = [0, 0, 0];

    X0 = viz_data.Populations{current_iter};
    Neighbors = viz_data.Neighbors{current_iter};
    ref = viz_data.Reference{current_iter};
    trajectory = viz_data.Trajectories{current_iter};
    
    %% (Content) Pareto Front
    PF = Problem.GetOptimum(100);
    h_PF = plot(ax, PF(:,1), PF(:,2), 'Color', 'k', 'LineWidth', 3);
    
    %% (Content) Neighbor set
    
    % Plot all neighbors in objective space
    all_neighbor_objs = [];
    for i = 1:length(Neighbors)
        all_neighbor_objs = [all_neighbor_objs; Neighbors{i}.objs];
    end
    all_neighbor_objs = setdiff(all_neighbor_objs, X0.objs, 'rows');
    h_n = scatter(ax, ...
    all_neighbor_objs(:,1), all_neighbor_objs(:,2), ...
        'SizeData', 60, ...
        'CData', neighbor_color, ...
        'Marker', 'diamond', ...        % optional: defaults to 'o'
        'MarkerFaceColor', 'flat', ... % required to apply CData as face color
        'MarkerEdgeColor', neighbor_color, ...
        'MarkerFaceAlpha', 1);


    h_ref = scatter(ax, ...
        ref(:,1), ref(:,2), ...
        'SizeData', 120, ...
        'CData', ref_color, ...
        'Marker', 'square', ...
        'MarkerFaceColor', 'flat', ...
        'MarkerEdgeColor', 'None', ...
        'MarkerFaceAlpha', 1);    
    
    %% (Content) X0 set
    X0_feasible = all(X0.cons <= 0, 2)'; X0_objs = X0.objs;
    
    h_fX0 = scatter(ax, ...
        X0_objs(X0_feasible,1), X0_objs(X0_feasible,2), ...
        'SizeData', 140, ...
        'CData', feasible_color, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'flat', ...
        'MarkerEdgeColor', 'none', ...
        'LineWidth', 1);
    h_ifX0 = scatter(ax, ...
        X0_objs(~X0_feasible,1), X0_objs(~X0_feasible,2), ...
        'SizeData', 140, ...
        'CData', feasible_color, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'none', ...
        'MarkerEdgeColor', feasible_color, ...
        'LineWidth', 3);
    
    % Plot GSA trajectories in objective space
    X1_feasible_plotted = false; X1_infeasible_plotted = false;
    pre = trajectory.pre; post = trajectory.post;
    h_dir = plot(ax, nan, nan, '-', ...
        'Color', traj_color, ...          % 1x3 RGB; lines don’t support RGBA
        'LineWidth', 3, ...
        'DisplayName', 'Normalized Direction');

    for j = 1:numel(pre)
        p0_objs = pre{j}.objs; num_tests = numel(post{j});
        for k = 1:num_tests
            p1_objs = post{j}(k).objs;
            % Calculate color based on step size
            t = (k-1)/(max(num_tests-1, 1));
            traj_color = [0.9 - 0.4*t, 0.3 - 0.2*t, 0.3 - 0.2*t];
            alpha = 1 - 0.5*t;
            
            %% (Content) GSA trajectory
            h_GSA = plot(ax, ...
                [p0_objs(1), p1_objs(1)], ...
                [p0_objs(2), p1_objs(2)], ...
                '-', 'Color', [traj_color, alpha], ...
                'LineWidth', 3);
            uistack(h_GSA, 'bottom');
        end
        p1_final_objs = post{j}(end).objs;
        p1_final_feasible = all(post{j}(end).cons <= 0, 2);
        if p1_final_feasible
            %% (Content) Feasible solution
            h_fX1 = scatter(ax, ...
                p1_final_objs(1), p1_final_objs(2), ...
                'SizeData', 140, ...
                'CData', final_color, ...
                'Marker', '^', ...
                'MarkerFaceColor', 'flat', ...
                'MarkerEdgeColor', 'none', ...
                'LineWidth', 1);
        else
            %% (Content) Infeasible solution
            h_ifX1 = scatter(ax, ...
                p1_final_objs(1), p1_final_objs(2), ...
                'SizeData', 140, ...
                'CData', final_color, ...
                'Marker', '^', ...
                'MarkerFaceColor', 'none', ...
                'MarkerEdgeColor', final_color, ...
                'LineWidth', 3);
        end
    end
    uistack(h_PF, 'bottom');
    
    % Add legend
    legend([h_PF, h_ref, h_n, h_fX0, h_ifX0, h_fX1, h_ifX1, h_GSA], ...
        {'True Pareto Set', ...
        'Reference Point', ...
        'Neighbors', ...
        'Feasible Solutions ($X_0$)', ...
        'Infeasible Solutions ($X_0$)', ...
        'Feasible Solutions ($X_1$)', ...
        'Infeasible Solutions ($X_1$)', ...
        'GSA Trajectory'}, 'interpreter', 'latex');
    legend(ax, 'Location', 'best');

    set(gca, 'FontSize', 24, 'FontName', 'Times');
    
    % EnlargeFont();
end



