function VisualizeNoExtraHV(filename, Problem)
    %% ===============================================================
    %  VisualizeNoExtraHV
    %  ---------------------------------------------------------------
    %  Visualizes the MOEA→GSA transition and interpolative trajectories.
    %  Each trajectory shows how solutions evolve across GSA iterations.
    %  ---------------------------------------------------------------

    data = load(filename);
    viz_data = data.viz_data;
    MOEA_POP = viz_data.MOEA_POP;
    MOEA_ITER = viz_data.MOEA_ITER;
    GSA_POP = viz_data.GSA_POP;
    GSA_ITER = viz_data.GSA_ITER;
    REFERENCE = viz_data.REFERENCE;
    % TRAJECTORY_ITERS = viz_data.TRAJECTORY.ITER;
    % TRAJECTORY_POPS = viz_data.TRAJECTORY.POP;
    AGSA_POP = viz_data.AGSA_POP;
    AGSA_ITER = viz_data.AGSA_ITER;
    FILENAME = viz_data.NAME;
    MOEA_FE = viz_data.MOEA_FE;
    MOEA_HVFE = viz_data.MOEA_HVFE;
    GSA_FE = viz_data.GSA_FE;
    GSA_HVFE = viz_data.GSA_HVFE;
    AGSA_FE = viz_data.AGSA_FE;
    AGSA_HVFE = viz_data.AGSA_HVFE;
    


    %% ===================== Figure Configuration =====================
    % if ishandle(1) && strcmp(get(1, 'Type'), 'figure')
    %     disp('Figure 1 exists.');
    %     fig = figure(1);
    % else
    disp('Figure 1 does not exist.');
    fig = figure('Position', [100, 100, 1200, 900], ...
                 'Name', 'GSA without incurring extra HV/FE');
    % end

    ax = axes('Parent', fig, 'Position', [0.1, 0.1, 0.85, 0.85]);
    cla(ax, 'reset'); hold(ax, 'on'); grid(ax, 'on'); box(ax, 'on'); axis(ax, 'tight');

    %% ===================== Title and Labels =====================
    moea_objs = MOEA_POP.objs; moea_cons = MOEA_POP.cons;
    gsa_objs  = GSA_POP.objs;  gsa_cons  = GSA_POP.cons;
    agsa_objs  = AGSA_POP.objs;  agsa_cons  = AGSA_POP.cons;
    % N = size(gsa_objs, 1);
    % agsa_objs = agsa_objs(end-N+1:end, :); agsa_cons = agsa_cons(end-N+1:end, :);

    HV0 = FeasibleCHV(REFERENCE, Flatten(moea_objs), Flatten(moea_cons));
    HVG = FeasibleCHV(REFERENCE, Flatten(gsa_objs),  Flatten(gsa_cons));
    HVA = FeasibleCHV(REFERENCE, Flatten(agsa_objs),  Flatten(agsa_cons));
    % title(ax, ...
    %     sprintf('Problem: %s. $\\mathrm{HV}:%.4f\\;\\rightarrow\\;%.4f$', class(Problem), HV0, HVF), ...
    %     'Interpreter', 'latex');
    xlabel(ax, '$f_1$', 'Interpreter', 'latex');
    ylabel(ax, '$f_2$', 'Interpreter', 'latex');

    %% ===================== Colors =====================
    ref_color  = [0, 0, 0];
    MOEA_color = [0.8, 0.2, 0.2];
    GSA_color  = [0.2, 0.6, 0.2];
    AGSA_color = [0.7412    0.5765    0.2000];
    cmap_traj  = [linspace(1,0,256)', linspace(0,1,256)', zeros(256,1)]; % red→green

    %% ===================== Contents =====================
    % True Pareto Front
    h_pf = DrawObjectives(ax, Problem);

    % Reference Point
    h_ref = scatter(ax, ...
        REFERENCE(:,1), REFERENCE(:,2), ...
        'SizeData', 140, ...
        'CData', ref_color, ...
        'Marker', 'square', ...
        'MarkerFaceColor', 'flat', ...
        'MarkerEdgeColor', 'none');

    % Last MOEA Population
    h_moea = scatter(ax, ...
        moea_objs(:,1), moea_objs(:,2), ...
        'SizeData', 120, ...
        'CData', MOEA_color, ...
        'Marker', 'x', ...
        'MarkerFaceColor', 'flat', ...
        'MarkerFaceAlpha', 1, ...
        'MarkerEdgeColor', MOEA_color, ...
        'LineWidth', 3);

    % Last Linear GSA Population
    % h_gsa = scatter(ax, ...
    %     gsa_objs(:,1), gsa_objs(:,2), ...
    %     'SizeData', 100, ...
    %     'CData', GSA_color, ...
    %     'Marker', 'diamond', ...
    %     'MarkerFaceColor', 'flat', ...
    %     'MarkerFaceAlpha', 1, ...
    %     'MarkerEdgeColor', 'none');

    % Last Adaptive GSA Population
    h_agsa = scatter(ax, ...
        agsa_objs(:,1), agsa_objs(:,2), ...
        'SizeData', 150, ...
        'CData', AGSA_color, ...
        'Marker', 'pentagram', ...
        'MarkerFaceColor', 'flat', ...
        'MarkerFaceAlpha', 1, ...
        'MarkerEdgeColor', 'none');

    uistack(h_moea, 'top');
    uistack(h_agsa, 'top');
    % uistack(h_gsa, 'bottom');

    %% ===================== GSA Trajectories =====================
    % fprintf('Plotting %d GSA trajectory iterations...\n', numel(TRAJECTORY_POPS));
    % 
    % N = viz_data.N;
    % for iter = 1:numel(TRAJECTORY_POPS)
    %     Xs = TRAJECTORY_POPS{iter};
    %     sub_pop = Xs(end-N+1:end);
    %     sub_objs = sub_pop.objs;  
    % 
    %     % Draw gradient trajectory (red→green scatter)
    %     nPts = size(sub_objs, 1);
    %     t = linspace(0, 1, nPts)'; % normalized
    %     C_traj = (1 - t) .* repmat(MOEA_color, nPts, 1) + t .* repmat(GSA_color, nPts, 1);
    % 
    %     h_traj = scatter(ax, ...
    %         sub_objs(:,1), sub_objs(:,2), ...
    %         'SizeData', 36, ...
    %         'CData', C_traj, ...
    %         'MarkerFaceColor', 'flat', ...
    %         'Marker', '.');
    % end

    %% ===================== Legend and Style =====================
    % legend(ax, [h_ref, h_moea, h_gsa, h_agsa, h_pf], ...
    %     {'Reference Point', ...
    %      sprintf('Last MOEA Pop. (iter %d, $\\mathrm{HV}:%.4f$, spent $\\mathrm{FE}:%d$, $\\mathrm{HV}$ calls:%d)', MOEA_ITER-1, HV0, MOEA_FE, MOEA_HVFE), ...
    %      sprintf('Fixed-step GSA Pop. (iter %d, $\\mathrm{HV}:%.4f$, spent $\\mathrm{FE}:%d$, $\\mathrm{HV}$ calls:%d)', GSA_ITER-1, HVG, GSA_FE, GSA_HVFE), ...
    %      sprintf('Adaptive GSA Pop. (iter %d, $\\mathrm{HV}:%.4f$, spent $\\mathrm{FE}:%d$, $\\mathrm{HV}$ calls:%d)', AGSA_ITER-1, HVA, AGSA_FE, AGSA_HVFE), ...
    %      'True Pareto Front'}, ...
    %      'Interpreter', 'latex', 'Location', 'best');
    legend(ax, [h_ref, h_moea, h_agsa, h_pf], ...
        {'Reference Point', ...
         sprintf('Last MOEA Pop. (iter %d, $\\mathrm{HV}:%.4f$, spent $\\mathrm{FE}:%d$, $\\mathrm{HV}$ calls:%d)', MOEA_ITER-1, HV0, MOEA_FE, MOEA_HVFE), ...
         sprintf('Adaptive GSA Pop. (iter %d, $\\mathrm{HV}:%.4f$, spent $\\mathrm{FE}:%d$, $\\mathrm{HV}$ calls:%d)', AGSA_ITER-1, HVA, AGSA_FE, AGSA_HVFE), ...
         'True Pareto Front'}, ...
         'Interpreter', 'latex', 'Location', 'best');

    set(ax, 'FontSize', 20, 'FontName', 'Times');
    axis(ax, 'tight');
    print(sprintf('./Visualization/images/eps_conversion/%s', FILENAME),'-depsc')
end
